In [ ]:
import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# -------------------------------------------------
# Create FrozenLake Environment
# -------------------------------------------------
env_desc = [
      "SFFF",
      "FFFF",
      "FHFH",
      "FFFG"
]


env = gym.make("FrozenLake-v1", desc=env_desc, is_slippery=True)
# write your code here

In [ ]:
# -------------------------------------------------
# Value Iteration Algorithm
# -------------------------------------------------

def value_iteration(env, gamma=0.99, theta=1e-8):
    """
    Performs value iteration and returns the optimal value function.
    """

    num_states = env.observation_space.n
    num_actions = env.action_space.n

    # Initialize value function
    V = np.zeros(num_states)

    iteration = 0

    while True:
        delta = 0
        iteration += 1

        for state in range(num_states):
            v = V[state]
            action_values = []

            for action in range(num_actions):
                q_value = 0

                # Transition probabilities
                for prob, next_state, reward, done in env.unwrapped.P[state][action]:
                    q_value += prob * (reward + gamma * V[next_state])

                action_values.append(q_value)

            V[state] = max(action_values)
            delta = max(delta, abs(v - V[state]))

        # Check convergence
        if delta < theta:
            break

    # Extract optimal policy
    policy = np.zeros(num_states, dtype=int)

    for state in range(num_states):
        action_values = []

        for action in range(num_actions):
            q_value = 0

            for prob, next_state, reward, done in env.unwrapped.P[state][action]:
                q_value += prob * (reward + gamma * V[next_state])

            action_values.append(q_value)

        policy[state] = np.argmax(action_values)

    return V, policy, iteration

In [ ]:
# -------------------------------------------------
# Run Value Iteration
# -------------------------------------------------

V, policy, iteration = value_iteration(env)

print("Optimal Value Function:")
print(V)

print("\nOptimal Policy:")
print(policy)

print("\nNumber of Iterations:", iteration)

Optimal Value Function:
[0.71758794 0.69380189 0.66725408 0.64762894 0.73933305 0.69104014
 0.66092611 0.64451219 0.78348219 0.         0.52485797 0.
 0.85137322 0.87717241 0.92955258 0.        ]

Optimal Policy:
[0 0 0 3 0 3 3 3 0 0 0 0 1 1 1 0]

Number of Iterations: 200


In [ ]:
# -------------------------------------------------
# Display Output
# -------------------------------------------------
print("Name: Jesubalan A")
print("Register Number: 212223240060")
print("Value Iteration Completed")
print("Number of Iterations:", iteration)

print("\nOptimal State-Value Function:")
print(np.round(V.reshape(4, 4), 4))

action_symbols = {
    0: "L",
    1: "D",
    2: "R",
    3: "U"
}

policy_grid = np.array(
    [action_symbols[action] for action in policy]
).reshape(4, 4)

print("\nOptimal Policy:")
print(policy_grid)

env.close()

Name: Jesubalan A
Register Number: 212223240060
Value Iteration Completed
Number of Iterations: 200

Optimal State-Value Function:
[[0.7176 0.6938 0.6673 0.6476]
 [0.7393 0.691  0.6609 0.6445]
 [0.7835 0.     0.5249 0.    ]
 [0.8514 0.8772 0.9296 0.    ]]

Optimal Policy:
[['L' 'L' 'L' 'U']
 ['L' 'U' 'U' 'U']
 ['L' 'L' 'L' 'L']
 ['D' 'D' 'D' 'L']]
